name: Example Workflow

on:
  push:
    branches:
      - main

env:
  BASE_URL: "https://example.com"
  FULL_URL: ${{ env.BASE_URL + '/api/v1' }}


jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "Base URL: $BASE_URL"
          echo "Full URL: $FULL_URL"




