name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: 'value'

    steps:
      - name: Define Variables
        id: defs
        run:
          echo "MY_VARIABLE=value" >> $GITHUB_ENV

      - name: Set New Variable Based on Existing Variable
        env:
          MY_SUB_VARIABLE: ${{ env.MY_VARIABLE}}
        run: echo "MY_SUB_VARIABLE=${{ env.MY_SUB_VARIABLE }}"


