name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://example.com"
    steps:
      - name: Set environment variable based on BASE_URL
        run: echo "Setting DEPLOY_URL to ${{ env.BASE_URL }}/deploy"
        env:
          DEPLOY_URL: ${{ env.BASE_URL }}/deploy
